# Kingsely Strategy Configuration
# MT5 Credentials - DO NOT COMMIT THIS FILE TO GIT

MT5_LOGIN = 298444748
MT5_PASSWORD = "P123456789a@"
MT5_SERVER = "Exness-MT5Trial9"

# Telegram Notifications (optional override)
TELEGRAM_BOT_TOKEN = "8441397981:AAHxmLmmMM-hiWMzCVpT4S-y4zzJMTUXYto"
TELEGRAM_CHAT_ID = "633857520"
TELEGRAM_ENABLED = True

# Strategy Parameters
KINGSELY_ONE_SIGNAL_PER_SETUP = False
KINGSELY_MAX_TRADES_PER_SETUP = 3

KINGSELY_BACKTEST_SYMBOL = 'GC=F'
KINGSELY_LIVE_SYMBOL = 'XAUUSDz'
KINGSELY_YAHOO_TO_MT5 = {'GC=F': 'XAUUSDz', 'GBPUSD=X': 'GBPUSDm', 'BTC-USD': 'BTCUSDm', '^NDX': 'NAS100m'}

# Structure detection
KINGSELY_SWING_LENGTH = 3
KINGSELY_OB_LOOKBACK = 20
KINGSELY_FVG_LOOKBACK = 30
KINGSELY_LIQUIDITY_LOOKBACK = 5

# HTF bias (1H)
KINGSELY_HTF_LOOKBACK_HOURS = 48
KINGSELY_REQUIRE_HTF_ZONE_CONFIRMATION = True

# 4H confirmation
KINGSELY_REQUIRE_4H_BIAS = False
KINGSELY_4H_AS_FILTER = False
KINGSELY_REQUIRE_4H_ZONE_CONFIRMATION = False
KINGSELY_4H_LOOKBACK_BARS = 24

# Breaker block
KINGSELY_REQUIRE_BREAKER_BLOCK = False
KINGSELY_BREAKER_BLOCK_4H = False
KINGSELY_REJECTION_WICK_RATIO = 0.5
KINGSELY_REJECTION_BODY_RATIO = 0.3

# 5M setup window
KINGSELY_M5_WINDOW_HOURS = 12
KINGSELY_USE_LIQ_LEVEL_AS_ZONE = True
KINGSELY_LIQ_ZONE_ATR_MULT = 0.5

# Entry logic
KINGSELY_ALLOW_SIMPLE_ZONE_ENTRY = True
KINGSELY_REQUIRE_5M_SWEEP = False

# Premium/Discount (ICT)
KINGSELY_USE_PREMIUM_DISCOUNT = False
KINGSELY_EQUILIBRIUM_LOOKBACK = 24
KINGSELY_EQUILIBRIUM_TF = 'H1'

# Filters
KINGSELY_MAX_SPREAD_POINTS = 50.0
KINGSELY_MAX_CANDLE_VOLATILITY_ATR_MULT = 4.0
KINGSELY_USE_NEWS_FILTER = True
KINGSELY_NEWS_BUFFER_MINUTES = 15

# Risk management
KINGSELY_RISK_PER_TRADE = 0.10
KINGSELY_MAX_TRADES_PER_SESSION = 3
KINGSELY_DAILY_LOSS_LIMIT_PCT = 1.0
KINGSELY_USE_TRAILING_STOP = True
KINGSELY_MIN_RR = 3.0

# Displacement candle
KINGSELY_DISPLACEMENT_RATIO = 0.5
KINGSELY_SL_BUFFER = 1.0

# Stop Loss method: 'HYBRID' or 'OB'
KINGSELY_SL_METHOD = 'OB'
KINGSELY_SL_ATR_MULT = 1.0
KINGSELY_SL_MICRO_TF = '1m'
